/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FileInterceptor } from "@nestjs/platform-express";
import { UserService } from "../user.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { MembershipFindManyArgs } from "../../membership/base/MembershipFindManyArgs";
import { Membership } from "../../membership/base/Membership";
import { MembershipWhereUniqueInput } from "../../membership/base/MembershipWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserCreateInput,
  })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        documents: data.documents
          ? {
              connect: data.documents,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        documentNumber: true,
        documentType: true,

        documents: {
          select: {
            id: true,
          },
        },

        email: true,
        familyNameAr: true,
        familyNameEn: true,
        firstNameAr: true,
        firstNameEn: true,
        gender: true,
        id: true,
        isCompanyRepresentative: true,
        isSpecialNeeds: true,
        mobile: true,
        password: true,
        phoneCountrycode: true,
        profilePhotoPublic: true,
        profilePhotoUrl: true,
        roles: true,
        secondNameAr: true,
        secondNameEn: true,
        sessionId: true,
        thirdNameAr: true,
        thirdNameEn: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        documentNumber: true,
        documentType: true,

        documents: {
          select: {
            id: true,
          },
        },

        email: true,
        familyNameAr: true,
        familyNameEn: true,
        firstNameAr: true,
        firstNameEn: true,
        gender: true,
        id: true,
        isCompanyRepresentative: true,
        isSpecialNeeds: true,
        mobile: true,
        password: true,
        phoneCountrycode: true,
        profilePhotoPublic: true,
        profilePhotoUrl: true,
        roles: true,
        secondNameAr: true,
        secondNameEn: true,
        sessionId: true,
        thirdNameAr: true,
        thirdNameEn: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        documentNumber: true,
        documentType: true,

        documents: {
          select: {
            id: true,
          },
        },

        email: true,
        familyNameAr: true,
        familyNameEn: true,
        firstNameAr: true,
        firstNameEn: true,
        gender: true,
        id: true,
        isCompanyRepresentative: true,
        isSpecialNeeds: true,
        mobile: true,
        password: true,
        phoneCountrycode: true,
        profilePhotoPublic: true,
        profilePhotoUrl: true,
        roles: true,
        secondNameAr: true,
        secondNameEn: true,
        sessionId: true,
        thirdNameAr: true,
        thirdNameEn: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserUpdateInput,
  })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          documents: data.documents
            ? {
                connect: data.documents,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          documentNumber: true,
          documentType: true,

          documents: {
            select: {
              id: true,
            },
          },

          email: true,
          familyNameAr: true,
          familyNameEn: true,
          firstNameAr: true,
          firstNameEn: true,
          gender: true,
          id: true,
          isCompanyRepresentative: true,
          isSpecialNeeds: true,
          mobile: true,
          password: true,
          phoneCountrycode: true,
          profilePhotoPublic: true,
          profilePhotoUrl: true,
          roles: true,
          secondNameAr: true,
          secondNameEn: true,
          sessionId: true,
          thirdNameAr: true,
          thirdNameEn: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          documentNumber: true,
          documentType: true,

          documents: {
            select: {
              id: true,
            },
          },

          email: true,
          familyNameAr: true,
          familyNameEn: true,
          firstNameAr: true,
          firstNameEn: true,
          gender: true,
          id: true,
          isCompanyRepresentative: true,
          isSpecialNeeds: true,
          mobile: true,
          password: true,
          phoneCountrycode: true,
          profilePhotoPublic: true,
          profilePhotoUrl: true,
          roles: true,
          secondNameAr: true,
          secondNameEn: true,
          sessionId: true,
          thirdNameAr: true,
          thirdNameEn: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/profilePhotoUrl")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: User,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadProfilePhotoUrl(
    @common.Param()
    params: UserWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<User> {
    return this.service.uploadProfilePhotoUrl(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/profilePhotoUrl")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadProfilePhotoUrl(
    @common.Param()
    params: UserWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadProfilePhotoUrl({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/profilePhotoUrl")
  @swagger.ApiOkResponse({
    type: User,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteProfilePhotoUrl(
    @common.Param()
    params: UserWhereUniqueInput
  ): Promise<User> {
    return this.service.deleteProfilePhotoUrl({
      where: params,
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/memberships")
  @ApiNestedQuery(MembershipFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "any",
  })
  async findMemberships(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Membership[]> {
    const query = plainToClass(MembershipFindManyArgs, request.query);
    const results = await this.service.findMemberships(params.id, {
      ...query,
      select: {
        club: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationYears: true,
        endDate: true,
        id: true,
        paidAmount: true,
        sourceType: true,
        startDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/memberships")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectMemberships(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/memberships")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateMemberships(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/memberships")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectMemberships(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
