/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClubWhereUniqueInput } from "../../club/base/ClubWhereUniqueInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsNumber,
  Max,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { DocumentUpdateManyWithoutMembershipsInput } from "./DocumentUpdateManyWithoutMembershipsInput";
import { EnumMembershipSourceType } from "./EnumMembershipSourceType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class MembershipUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ClubWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClubWhereUniqueInput)
  @IsOptional()
  @Field(() => ClubWhereUniqueInput, {
    nullable: true,
  })
  club?: ClubWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  durationYears?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  paidAmount?: Decimal;

  @ApiProperty({
    required: false,
    type: () => DocumentUpdateManyWithoutMembershipsInput,
  })
  @ValidateNested()
  @Type(() => DocumentUpdateManyWithoutMembershipsInput)
  @IsOptional()
  @Field(() => DocumentUpdateManyWithoutMembershipsInput, {
    nullable: true,
  })
  paymentProofUrl?: DocumentUpdateManyWithoutMembershipsInput;

  @ApiProperty({
    required: false,
    enum: EnumMembershipSourceType,
  })
  @IsEnum(EnumMembershipSourceType)
  @IsOptional()
  @Field(() => EnumMembershipSourceType, {
    nullable: true,
  })
  sourceType?: "NEW" | "EXISTING_OFFSYSTEM" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { MembershipUpdateInput as MembershipUpdateInput };
