/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MembershipService } from "../membership.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MembershipCreateInput } from "./MembershipCreateInput";
import { Membership } from "./Membership";
import { MembershipFindManyArgs } from "./MembershipFindManyArgs";
import { MembershipWhereUniqueInput } from "./MembershipWhereUniqueInput";
import { MembershipUpdateInput } from "./MembershipUpdateInput";
import { DocumentFindManyArgs } from "../../document/base/DocumentFindManyArgs";
import { Document } from "../../document/base/Document";
import { DocumentWhereUniqueInput } from "../../document/base/DocumentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MembershipControllerBase {
  constructor(
    protected readonly service: MembershipService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Membership })
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MembershipCreateInput,
  })
  async createMembership(
    @common.Body() data: MembershipCreateInput
  ): Promise<Membership> {
    return await this.service.createMembership({
      data: {
        ...data,

        club: {
          connect: data.club,
        },

        user: {
          connect: data.user,
        },
      },
      select: {
        club: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationYears: true,
        endDate: true,
        id: true,
        paidAmount: true,
        sourceType: true,
        startDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Membership] })
  @ApiNestedQuery(MembershipFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async memberships(@common.Req() request: Request): Promise<Membership[]> {
    const args = plainToClass(MembershipFindManyArgs, request.query);
    return this.service.memberships({
      ...args,
      select: {
        club: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationYears: true,
        endDate: true,
        id: true,
        paidAmount: true,
        sourceType: true,
        startDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Membership })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async membership(
    @common.Param() params: MembershipWhereUniqueInput
  ): Promise<Membership | null> {
    const result = await this.service.membership({
      where: params,
      select: {
        club: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationYears: true,
        endDate: true,
        id: true,
        paidAmount: true,
        sourceType: true,
        startDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Membership })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MembershipUpdateInput,
  })
  async updateMembership(
    @common.Param() params: MembershipWhereUniqueInput,
    @common.Body() data: MembershipUpdateInput
  ): Promise<Membership | null> {
    try {
      return await this.service.updateMembership({
        where: params,
        data: {
          ...data,

          club: {
            connect: data.club,
          },

          user: {
            connect: data.user,
          },
        },
        select: {
          club: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          durationYears: true,
          endDate: true,
          id: true,
          paidAmount: true,
          sourceType: true,
          startDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Membership })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMembership(
    @common.Param() params: MembershipWhereUniqueInput
  ): Promise<Membership | null> {
    try {
      return await this.service.deleteMembership({
        where: params,
        select: {
          club: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          durationYears: true,
          endDate: true,
          id: true,
          paidAmount: true,
          sourceType: true,
          startDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/paymentProofUrl")
  @ApiNestedQuery(DocumentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Document",
    action: "read",
    possession: "any",
  })
  async findPaymentProofUrl(
    @common.Req() request: Request,
    @common.Param() params: MembershipWhereUniqueInput
  ): Promise<Document[]> {
    const query = plainToClass(DocumentFindManyArgs, request.query);
    const results = await this.service.findPaymentProofUrl(params.id, {
      ...query,
      select: {
        application: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        fileName: true,
        fileUrl: true,
        id: true,

        memberships: {
          select: {
            id: true,
          },
        },

        objectId: true,
        requestId: true,
        requestType: true,
        requestubype: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/paymentProofUrl")
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "update",
    possession: "any",
  })
  async connectPaymentProofUrl(
    @common.Param() params: MembershipWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentProofUrl: {
        connect: body,
      },
    };
    await this.service.updateMembership({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/paymentProofUrl")
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "update",
    possession: "any",
  })
  async updatePaymentProofUrl(
    @common.Param() params: MembershipWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentProofUrl: {
        set: body,
      },
    };
    await this.service.updateMembership({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/paymentProofUrl")
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "update",
    possession: "any",
  })
  async disconnectPaymentProofUrl(
    @common.Param() params: MembershipWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentProofUrl: {
        disconnect: body,
      },
    };
    await this.service.updateMembership({
      where: params,
      data,
      select: { id: true },
    });
  }
}
