/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Club } from "../../club/base/Club";

import {
  ValidateNested,
  IsDate,
  IsString,
  MaxLength,
  IsNumber,
  Max,
  IsOptional,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { Document } from "../../document/base/Document";
import { EnumMembershipSourceType } from "./EnumMembershipSourceType";
import { User } from "../../user/base/User";

@ObjectType()
class Membership {
  @ApiProperty({
    required: true,
    type: () => Club,
  })
  @ValidateNested()
  @Type(() => Club)
  club?: Club;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  durationYears!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endDate!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  paidAmount!: Decimal;

  @ApiProperty({
    required: false,
    type: () => [Document],
  })
  @ValidateNested()
  @Type(() => Document)
  @IsOptional()
  paymentProofUrl?: Array<Document>;

  @ApiProperty({
    required: false,
    enum: EnumMembershipSourceType,
  })
  @IsEnum(EnumMembershipSourceType)
  @IsOptional()
  @Field(() => EnumMembershipSourceType, {
    nullable: true,
  })
  sourceType?: "NEW" | "EXISTING_OFFSYSTEM" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startDate!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  status!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  user?: User;
}

export { Membership as Membership };
