/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Membership } from "./Membership";
import { MembershipCountArgs } from "./MembershipCountArgs";
import { MembershipFindManyArgs } from "./MembershipFindManyArgs";
import { MembershipFindUniqueArgs } from "./MembershipFindUniqueArgs";
import { CreateMembershipArgs } from "./CreateMembershipArgs";
import { UpdateMembershipArgs } from "./UpdateMembershipArgs";
import { DeleteMembershipArgs } from "./DeleteMembershipArgs";
import { DocumentFindManyArgs } from "../../document/base/DocumentFindManyArgs";
import { Document } from "../../document/base/Document";
import { Club } from "../../club/base/Club";
import { User } from "../../user/base/User";
import { MembershipService } from "../membership.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Membership)
export class MembershipResolverBase {
  constructor(
    protected readonly service: MembershipService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "any",
  })
  async _membershipsMeta(
    @graphql.Args() args: MembershipCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Membership])
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "any",
  })
  async memberships(
    @graphql.Args() args: MembershipFindManyArgs
  ): Promise<Membership[]> {
    return this.service.memberships(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Membership, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "own",
  })
  async membership(
    @graphql.Args() args: MembershipFindUniqueArgs
  ): Promise<Membership | null> {
    const result = await this.service.membership(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Membership)
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "create",
    possession: "any",
  })
  async createMembership(
    @graphql.Args() args: CreateMembershipArgs
  ): Promise<Membership> {
    return await this.service.createMembership({
      ...args,
      data: {
        ...args.data,

        club: {
          connect: args.data.club,
        },

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Membership)
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "update",
    possession: "any",
  })
  async updateMembership(
    @graphql.Args() args: UpdateMembershipArgs
  ): Promise<Membership | null> {
    try {
      return await this.service.updateMembership({
        ...args,
        data: {
          ...args.data,

          club: {
            connect: args.data.club,
          },

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Membership)
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "delete",
    possession: "any",
  })
  async deleteMembership(
    @graphql.Args() args: DeleteMembershipArgs
  ): Promise<Membership | null> {
    try {
      return await this.service.deleteMembership(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Document], { name: "paymentProofUrl" })
  @nestAccessControl.UseRoles({
    resource: "Document",
    action: "read",
    possession: "any",
  })
  async findPaymentProofUrl(
    @graphql.Parent() parent: Membership,
    @graphql.Args() args: DocumentFindManyArgs
  ): Promise<Document[]> {
    const results = await this.service.findPaymentProofUrl(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Club, {
    nullable: true,
    name: "club",
  })
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "read",
    possession: "any",
  })
  async getClub(@graphql.Parent() parent: Membership): Promise<Club | null> {
    const result = await this.service.getClub(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Membership): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
