/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClubWhereUniqueInput } from "../../club/base/ClubWhereUniqueInput";

import {
  ValidateNested,
  IsString,
  MaxLength,
  IsDate,
  IsNumber,
  Max,
  IsOptional,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { DocumentCreateNestedManyWithoutMembershipsInput } from "./DocumentCreateNestedManyWithoutMembershipsInput";
import { EnumMembershipSourceType } from "./EnumMembershipSourceType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class MembershipCreateInput {
  @ApiProperty({
    required: true,
    type: () => ClubWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClubWhereUniqueInput)
  @Field(() => ClubWhereUniqueInput)
  club!: ClubWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  durationYears!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endDate!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  paidAmount!: Decimal;

  @ApiProperty({
    required: false,
    type: () => DocumentCreateNestedManyWithoutMembershipsInput,
  })
  @ValidateNested()
  @Type(() => DocumentCreateNestedManyWithoutMembershipsInput)
  @IsOptional()
  @Field(() => DocumentCreateNestedManyWithoutMembershipsInput, {
    nullable: true,
  })
  paymentProofUrl?: DocumentCreateNestedManyWithoutMembershipsInput;

  @ApiProperty({
    required: false,
    enum: EnumMembershipSourceType,
  })
  @IsEnum(EnumMembershipSourceType)
  @IsOptional()
  @Field(() => EnumMembershipSourceType, {
    nullable: true,
  })
  sourceType?: "NEW" | "EXISTING_OFFSYSTEM" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startDate!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  status!: string;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  user!: UserWhereUniqueInput;
}

export { MembershipCreateInput as MembershipCreateInput };
