/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClubService } from "../club.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClubCreateInput } from "./ClubCreateInput";
import { Club } from "./Club";
import { ClubFindManyArgs } from "./ClubFindManyArgs";
import { ClubWhereUniqueInput } from "./ClubWhereUniqueInput";
import { ClubUpdateInput } from "./ClubUpdateInput";
import { MembershipFindManyArgs } from "../../membership/base/MembershipFindManyArgs";
import { Membership } from "../../membership/base/Membership";
import { MembershipWhereUniqueInput } from "../../membership/base/MembershipWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClubControllerBase {
  constructor(
    protected readonly service: ClubService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Club })
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ClubCreateInput,
  })
  async createClub(@common.Body() data: ClubCreateInput): Promise<Club> {
    return await this.service.createClub({
      data: data,
      select: {
        category: true,
        ccode: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Club] })
  @ApiNestedQuery(ClubFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async clubs(@common.Req() request: Request): Promise<Club[]> {
    const args = plainToClass(ClubFindManyArgs, request.query);
    return this.service.clubs({
      ...args,
      select: {
        category: true,
        ccode: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Club })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async club(
    @common.Param() params: ClubWhereUniqueInput
  ): Promise<Club | null> {
    const result = await this.service.club({
      where: params,
      select: {
        category: true,
        ccode: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Club })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ClubUpdateInput,
  })
  async updateClub(
    @common.Param() params: ClubWhereUniqueInput,
    @common.Body() data: ClubUpdateInput
  ): Promise<Club | null> {
    try {
      return await this.service.updateClub({
        where: params,
        data: data,
        select: {
          category: true,
          ccode: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Club })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClub(
    @common.Param() params: ClubWhereUniqueInput
  ): Promise<Club | null> {
    try {
      return await this.service.deleteClub({
        where: params,
        select: {
          category: true,
          ccode: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/memberships")
  @ApiNestedQuery(MembershipFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "any",
  })
  async findMemberships(
    @common.Req() request: Request,
    @common.Param() params: ClubWhereUniqueInput
  ): Promise<Membership[]> {
    const query = plainToClass(MembershipFindManyArgs, request.query);
    const results = await this.service.findMemberships(params.id, {
      ...query,
      select: {
        club: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationYears: true,
        endDate: true,
        id: true,
        paidAmount: true,
        sourceType: true,
        startDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/memberships")
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "update",
    possession: "any",
  })
  async connectMemberships(
    @common.Param() params: ClubWhereUniqueInput,
    @common.Body() body: MembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        connect: body,
      },
    };
    await this.service.updateClub({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/memberships")
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "update",
    possession: "any",
  })
  async updateMemberships(
    @common.Param() params: ClubWhereUniqueInput,
    @common.Body() body: MembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        set: body,
      },
    };
    await this.service.updateClub({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/memberships")
  @nestAccessControl.UseRoles({
    resource: "Club",
    action: "update",
    possession: "any",
  })
  async disconnectMemberships(
    @common.Param() params: ClubWhereUniqueInput,
    @common.Body() body: MembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        disconnect: body,
      },
    };
    await this.service.updateClub({
      where: params,
      data,
      select: { id: true },
    });
  }
}
